setup: implicitly initialize the OpenBMC submodule
Signed-off-by: Marcello Sylvester Bauer <marcello.bauer@9elements.com>

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -100,6 +100,13 @@ else
     EXIT_CMD="return"
 fi
 
+if [ ! -f "openbmc/oe-init-build-env" ]; then
+    if ! git submodule update --init --recursive; then
+        echo "ERROR: Failed to initialize OpenBMC submodule" >&2
+        ${EXIT_CMD} 1
+    fi
+fi
+
 if [ -z "$1" ]; then
     echo Target machine must be specified. Use one of:
     echo
